### ISSUE TITLE
CT no direction description found for balloon moving direction null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#521] opened 2021-08-02 18:01 UTC
```
balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627909909385%22%2C%22timestamp%22%3A1627911038356%7D
Uncaught Error: Uncaught Error: Assertion failed: no direction description found for balloon moving direction null
Error: Assertion failed: no direction description found for balloon moving direction null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/assert/js/assert.js:25:13)
at BalloonPositionDescriber.getReleaseDirectionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonPositionDescriber.js:687:15)
at BalloonPositionDescriber.getDirectionChangedDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonPositionDescriber.js:791:36)
at BalloonDescriber.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonDescriber.js:760:66)
at BalloonNode.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BalloonNode.js:446:20)
at BASEView.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:201:27)
at PhetioStateEngine.updateViews (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/phet-io/js/PhetioStateEngine.js:292:70)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/phet-io/js/PhetioStateEngine.js:255:10)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/phet-io/js/PhetioStateEngine.js:266:10)
at PhetioEngine.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627909909385/phet-io/js/phetioEngine.js:1041:32)
id: Bayes Chrome
Snapshot from 8/2/2021, 7:11:49 AM
```

**Comment by jessegreenberg** [comment] 2021-08-02 18:08
Thanks @KatieWoe, will take a look. Adding label because this is blocking and we are hoping to grab RC shas soon.

**Comment by jbphet** [comment] 2021-08-02 22:47
@jessegreenberg and I talked and I'm going to take a look at this while he is investigating another blocking issue.

**Comment by jbphet** [comment] 2021-08-02 22:51
After some investigation, I have a set of steps through which this can be manually replicated:

1. Load the state wrapper
2. Set the "Set State Rate" to zero
3. In the upstream sim, turn on the green balloon and move it to the sweater
4. Press the "Set State Now" button
5. Preset the reset button in the upstream sim
6. Press the "Set State Now" button
7. Turn the green balloon on again in the upstream sim
8. Press the "Set State Now" button

**Comment by jbphet** [comment] 2021-08-02 23:11
The problem is occurring when the downstream sim is trying to describe the direction of travel of the green balloon, but it only occurs in certain unusual circumstances, such as the sequence I've described above.  It happens when the value of the `directionProperty` in the balloon is `null`, which only occurs after a reset.  The `BalloonDescriber` class barfs when asked to describe a direction value of `null`.

I have a simple code change that will make the problem go away, and I'll commit it shortly.  In essence, it tells the describer not to try to describe a direction of `null`, which seems pretty reasonable.  I could dig deeper and figure out more about exactly why this situation is coming up, but it doesn't really seem worth it, since a lot has changed in both phet-io and description recently, so I might well be solving a problem that doesn't need to be solved.  With that in mind, I'm going to list my open questions, commit the fix, and then turn it over to @jessegreenberg for review.

My open questions are:
- Why is the describer being stepped during phet-io state setting?  Won't this cause a bunch of things to come out of a screen reader whenever state is being set?  I'll add an agenda item for the next phet-io meeting on this topic.
- The `directionProperty` gets set to null on every reset.  Why does this problem only occur during phet-io state setting and not other times?
- Is it a bad design practice to have state values that can't be described by the thing that is supposed to be describing them?  It kind of seems like it to me, but it might be a good idea to have some design guidance around this, perhaps something like "There should be explicit handling in any describer for all possible values that are described quantity can take on."

**Comment by jbphet** [comment] 2021-08-02 23:14
@jessegreenberg - I've committed a proposed fix for this issue.  Please review and make sure that it won't cause any negative unanticipated consequences for description.

**Comment by jbphet** [comment] 2021-08-02 23:28
@jessegreenberg - One other thought on this.  The solution I committed above handles the specific case of preventing description from occurring when the direction of a balloon is set to `null`, but maybe we should also add code to prevent _any_ description from being invoked during the setting of phet-io state.  I've added code to prevent things during phet-io state setting before, so it is not uncommon to do something like this.  If you'd like to see some examples in the code base, search on `phet.joist.sim.isSettingPhetioStateProperty.value`.  There are `if` clauses in lots of places that use this.

**Comment by jessegreenberg** [comment] 2021-08-06 16:59
This change looks like a reasonable way to prevent the issue, thanks @jbphet.

>Why is the describer being stepped during phet-io state setting? Won't this cause a bunch of things to be said by a screen reader whenever state is being set?
> but maybe we should also add code to prevent any description from being invoked during the setting of phet-io state.

This is correct, we should prevent alerts in this case for the reason you described. But I think it would be better to prevent this in common code in AriaHerald or UtteranceQueue rather than put these checks in sim describer code. Ill make an issue in utterance-queue to consider this.

I confirmed this issue is no longer on CT, closing.

**Closed by jessegreenberg** 2021-08-06 16:59 UTC
Labels: status:ready-for-review, type:automated-testing, status:blocks-sim-publication
