### ISSUE TITLE
missing images/license.txt and assets/

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#72] opened 2013-09-05 17:36 UTC
All images in images/ must be accounted for in images/license.txt.

And any images that were created by PhET should have their original source files (.ai, .psd,...) checked in to assets/.

**Comment by jonathanolson** [comment] 2017-04-14 00:02
Looks like 1.2 is going to go out without resolving this?:

```
>> license exception for BALLOONS_AND_STATIC_ELECTRICITY/charge-transfer-beep.mp3: This might NOT meet the license requirements for PhET, the use is t
emporary until something new is created
>> license exception for BALLOONS_AND_STATIC_ELECTRICITY/charge-transfer-beep.ogg: This might NOT meet the license requirements for PhET, the use is t
emporary until something new is created
>> license exception for BALLOONS_AND_STATIC_ELECTRICITY/bounds-beep.mp3: This might NOT meet the license requirements for PhET, the use is temporary
until something new is created
>> license exception for BALLOONS_AND_STATIC_ELECTRICITY/bounds-beep.ogg: This might NOT meet the license requirements for PhET, the use is temporary
until something new is created
```

**Comment by pixelzoom** [comment] 2017-04-14 01:25
@jessegreenberg created audio/license.json and appears to have pushed the audio files in question. Perhaps he can elaborate.

**Comment by jessegreenberg** [comment] 2017-04-14 05:24
Thanks for catching, assets removed for 1.2 branch and won't be part of the release.  They should be removed from master at this point too, we were playing with some ideas but nothing was meant long term use at this point.

**Comment by jessegreenberg** [comment] 2017-08-16 03:16
These assets were removed, and this issue should have been closed long ago. Closing.

**Comment by jessegreenberg** [comment] 2017-08-16 03:20
But this issue was originally about missing image assets. It looks like the balloons are still missing from assets/.  @arouinfar do you know if we can find these somewhere?

**Comment by arouinfar** [comment] 2017-08-16 16:34
@jessegreenberg BASE predates me, so I don't know who would've created the balloon assets, but maybe @ariel-phet has some idea.

**Comment by arouinfar** [comment] 2017-08-16 16:36
I didn't see any BASE-related artwork backed up on Drive.

**Comment by pixelzoom** [comment] 2017-08-16 16:41
Perhaps the BASE artwork lives in Unfuddle, since it was originally a Java sim?

**Comment by pixelzoom** [comment] 2017-08-16 16:42
In Unfuddle SVN, trunk/simulations-java/simulations/balloons/assets/, I see:

balloon-meg.gif
sweater-300x436.gif

**Comment by arouinfar** [comment] 2017-08-16 16:44
Good idea @pixelzoom, but I don't think those are the assets we're looking for
![sweater-300x436](https://user-images.githubusercontent.com/8419308/29374745-cdf281f6-826f-11e7-8acf-1df347c0c02a.gif)
![balloon-meg](https://user-images.githubusercontent.com/8419308/29374744-d7a156f0-826f-11e7-8d1d-3867eeec8409.gif)

**Comment by ariel-phet** [comment] 2017-08-28 16:36
@arouinfar @jessegreenberg - my guess is the balloons were drawn by Noah P. 

Perhaps the easiest thing would be to get Cheryl to redraw the balloons so we have a current .ai file

My guess is she will be able to reproduce these extremely quickly.

**Comment by arouinfar** [comment] 2017-08-28 20:17
@ariel-phet I created a task for Cheryl to re-draw the balloons (referenced above), so unassigning myself.

**Comment by arouinfar** [comment] 2017-09-11 18:25
@jessegreenberg I've emailed you the new balloon assets.

**Comment by jessegreenberg** [comment] 2017-09-28 18:32
I added the new assets, they are looking great.
![capture](https://user-images.githubusercontent.com/6396244/30983893-fdd485f4-a448-11e7-9fd5-c5e32c47baf9.PNG)

**Comment by jessegreenberg** [comment] 2017-09-28 18:50
Since we checked in the balloon .ai assets we now have all assets for this sim, There is also an images/license.json.  I think this issue can be closed.

**Closed by jessegreenberg** 2017-09-28 18:50 UTC
Labels: design:artwork, type:licensing
