### ISSUE TITLE
Can't pick up charges and too few dragging alerts (JAWS 18 and IE 11)

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#305] opened 2017-09-25 19:15 UTC
Using sim version 1.4.0-dev.4 and JAWS 18 with IE 11, user was not able to pick up charges from sweater when rubbing the balloon on the sweater.

Also, very few dragging alerts fired while moving across the Play Area
-  Only got dragging alerts every 3 or 4 key presses. User found that silent key presses were not reassuring. @jessegreenberg, could this be due to the described grid cell design, i.e., only mentioning a change based on distance through a grid cell?
- Note that user did get the Wall alert once they were at the wall.
- Note that user verbosity setting were set to "most"

**Comment by jessegreenberg** [comment] 2017-09-25 19:25
> user was not able to pick up charges from sweater when rubbing the balloon on the sweater.

@terracoda were you able to  see  the  user's  screen? We have  seen JAWS perform quite poorly when the DOM changes frequently, if I were to  guess I  would say this  is caused by #288.

**Comment by terracoda** [comment] 2017-09-25 19:27
@jessegreenberg, I was able to see the user's screen, and I could faintly hear the screen reader.

**Comment by jessegreenberg** [comment] 2017-09-25 19:34
@terracoda great! Did the movement seem particularly slow or sluggish?

> could this be due to the described grid cell design, i.e., only mentioning a change based on distance through a grid cell?

Possibly, Ill see if I can reproduce the problem. Alerts are limited by progress through a grid cell as well as time. There is a refresh rate of  ~2 seconds, if button was pressed faster than that it might might have been lost.  Maybe we need to  revert to linking alerts to key presses so something is heard every key press but also support continuous motion with a finger/mouse dragging?

**Comment by terracoda** [comment] 2017-09-25 19:38
No, it did not seem too sluggish. It might have been a little sluggish, but I have seen worse. And it was regular movement.

**Comment by jessegreenberg** [comment] 2017-09-28 15:17
This and #306 sound like performance issues to me, I am not able to reproduce this on my machine.

**Comment by jessegreenberg** [comment] 2018-03-31 17:59
This issue is fixed with changes made for https://github.com/phetsims/coulombs-law/issues/41. Also, performance with JAWS has been generally better on Firefox and we no longer target IE11 for a11y. Closing.

**Closed by jessegreenberg** 2018-03-31 18:00 UTC
Labels: design:a11y, type:performance
