### ISSUE TITLE
using JAWS, pressing space multiple times in balloons checkbox shifts keyboard navigation focus

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/balloons-and-static-electricity#404] opened 2018-05-15 23:27 UTC
<b>Test Device</b>

Hanson

<b>Operating System</b>

Windows 10

<b>Browser</b>

Firefox 60.0

<b>Problem Description</b>

For phetsims/QA/issues/112. If you tab to the balloons checkbox while JAWS is running and then press space multiple times, the keyboard navigation focus will shift to something else.

I've seen it shift to the following:
- One of the balloons
- The "Remove Wall" button
- Seemingly nothing

<b>Steps to Reproduce</b>

Tab to the balloons checkbox, and then press space multiple times.

<b>Visuals</b>

![base](https://user-images.githubusercontent.com/31285590/40088425-554b5cac-5864-11e8-90ed-dbeb43ec16ec.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Balloons and Static Electricity‬
URL: https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-dev.21/phet/balloons-and-static-electricity_all_phet_debug.html?accessibility
Version: 1.4.0-dev.21 2018-04-04 18:25:56 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Language: en-US
Window: 1280x606
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"balloons-and-static-electricity":{"sha":"f4f3cc64","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"bc7c5d1f","branch":"master"},"dot":{"sha":"e5489d18","branch":"master"},"joist":{"sha":"2cf256a9","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"b6c2b0f5","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"de004c6e","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"4a4afee2","branch":"master"},"scenery-phet":{"sha":"e68ebc03","branch":"master"},"sherpa":{"sha":"bb14a03a","branch":"master"},"sun":{"sha":"8a187c9f","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}

</details>

**Comment by lmulhall-phet** [comment] 2018-05-15 23:29
Possibly related to #293 and #308?

**Comment by lmulhall-phet** [comment] 2018-05-15 23:31
@jessegreenberg it would be useful to know how you were able to figure out where the focus is by doing something with the console.

**Comment by jessegreenberg** [comment] 2018-05-16 15:32
Thanks @lmulhall-phet, weird.

> it would be useful to know how you were able to figure out where the focus is by doing something with the console.

Sure, In the console, I added 
```js
window.setInterval( function() {
  console.log( document.activeElement );
}, 1000 );
```
1000 is the delay in ms, that can be tweaked if you want it faster or slower. This will tell you which DOM element has focus, which may be enough to indicate which scenery Node should have focus.

**Comment by jessegreenberg** [comment] 2018-05-16 17:47
This also sounds performance related, like the virtual cursor isn't able to keep up with browser focus. @lmulhall-phet are you able to reproduce this in FF ESR 52?

**Comment by jessegreenberg** [comment] 2018-05-16 17:59
I am not able to reproduce this with FF ESR 52. I think we need to decide whether we support "latest" FF or FF ESR 52.

**Comment by lmulhall-phet** [comment] 2018-05-16 19:48
@jessegreenberg I'm sort of torn on this...
1. https://support.mozilla.org/en-US/kb/can-i-use-my-screen-reader-new-firefox
2. http://www.freedomscientific.com/downloads/JAWS/JAWSWhatsNew#Enhancements
Performance is much better with FF ESR, but it seems like JAWS is trying to cater to those who transition to FF 60. The above links are pertinent.

**Comment by lmulhall-phet** [comment] 2018-05-16 19:50
In the "Web Browsers" section of the second link:
> JAWS 2018 now includes improvements necessary for users who move to Mozilla FireFox version 60, expected to release within the month. It is advised that JAWS users remain on the ESR version of FireFox until Mozilla officially releases version 60.

**Comment by lmulhall-phet** [comment] 2018-05-16 19:57
Long term, it seems like a good idea to support the latest version of FF, even though it may cause headaches in the short term.

**Comment by jessegreenberg** [comment] 2018-05-16 19:58
@lmulhall-phet I am equally torn, I agree with your interpretation. I agree that is the long term goal, but I want to avoid substantial short term work now if FF is going to significantly improve their performance anyway.

**Comment by lmulhall-phet** [comment] 2018-05-16 20:09
@jessegreenberg it sounds like we should support ESR 52 for now, and figure out when we should transition to FF 60? Maybe I'll continue to test sims on both versions, and if we see better performance on FF 60, we can begin the transition? What are your thoughts on this approach?

**Comment by lmulhall-phet** [comment] 2018-05-16 21:10
@jessegreenberg I also cannot reproduce on FF ESR 52.

**Comment by jessegreenberg** [comment] 2018-05-16 21:57
Thanks @lmulhall-phet. 

Regarding https://github.com/phetsims/balloons-and-static-electricity/issues/404#issuecomment-389649334,
That sounds reasonable to me, lets proceed with FF ESR 52 since that is the one that really works for now. I made an issue https://github.com/phetsims/a11y-research/issues/102 to discuss this in detail.

**Comment by jessegreenberg** [comment] 2018-05-18 00:19
I expect that we will proceed with FF 60 based on recent comments in https://github.com/phetsims/a11y-research/issues/102.

**Comment by jessegreenberg** [comment] 2018-05-18 00:25
...sometimes.

**Comment by jessegreenberg** [comment] 2018-05-18 00:28
I am guessing this is performance related, or related to our rapidly changing DOM but we should test a JSFiddle just in case.

**Comment by terracoda** [comment] 2018-05-18 15:05
@jessegreenberg, you have likely already given this great thought, but we might have to manage focus more tightly. Focus is easily lost if things are appearing and disappearing in the DOM. If focus is on an element that disappears the browser will try to put focus somewhere for us.

I am not sure how tightly we manage focus already??

**Comment by jessegreenberg** [comment] 2018-05-18 15:18
Good point @terracoda, we definitely need manage focus in those cases but I don't think that is what is happening here. So far my understanding of this issue is that JAWS is making focus to to the previous focusable element after clicking a button or checkbox that doesn't change.

**Comment by terracoda** [comment] 2018-05-29 19:51
@jessegreenberg, is it possible just to make sure we tell the browser where focus should be after an interaction?

Buttons can change context or not change context.:
- For example a button that opens a dialog is a change in context and focus has to be put in the dialog on the intended element. This does not happen by default by the browser.
- The Two-balloon Experiment, checkbox, it is not a change in context. Focus must remain on the checkbox. The user needs to Shift Tab or Arrow back or whatever to find the added balloon.
- The Remove/Add Wall button is also not a change in context. Focus must remain on the button when the button is pressed, regardless of the label text changing to "Add Wall" or "Remove Wall".

Just out of curiosity, how is the changed button created in the PDOM? Is it disappearing and reappearing or just getting new label text? 

Also, I am wondering how likely is it for a user to pound away on a single button? Does this happen on after a couple of quick toggles, or many quick toggles?

**Comment by jessegreenberg** [comment] 2018-06-05 22:36
I am seeing this bug with JAWS in this most basic HTML:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
  </head>
  <body>
    <button id="button1">Button 1</button>
    <button id="button2">Button 2</button>
    <button id="button3">Button 3</button>
    <button id="button4">Button 4</button>

    <p id="readout" aria-live="polite">Readout</p>
  </body>

<script>
  document.getElementById( 'button1' ).addEventListener( 'click', function( event ) {
    document.getElementById( 'readout' ).innerHTML = "button 1 clicked";
  } );

  document.getElementById( 'button2' ).addEventListener( 'click', function( event ) {
    document.getElementById( 'readout' ).innerHTML = "button 2 clicked";
  } );

  document.getElementById( 'button3' ).addEventListener( 'click', function( event ) {
    document.getElementById( 'readout' ).innerHTML = "button 3 clicked";
  } );

  document.getElementById( 'button4' ).addEventListener( 'click', function( event ) {
    document.getElementById( 'readout' ).innerHTML = "button 4 clicked";
  } );
</script>
</html>
```
To reproduce:
- Tab to button 2
- Press spacebar (button 2 gets clicked)
- Press spacebar (focus moves to button 1 and button 1 gets clicked)

**Comment by jessegreenberg** [comment] 2018-06-05 22:44
> is it possible just to make sure we tell the browser where focus should be after an interaction

It is unclear, but it could be a lot of work/exploration. I don't think it is worthwhile if JAWS has this issue on every webpage in FF.

> Just out of curiosity, how is the changed button created in the PDOM? Is it disappearing and reappearing or just getting new label text

In the case of BASE, buttons are just getting new label/inner text. I was worried about this too @terracoda, but https://github.com/phetsims/balloons-and-static-electricity/issues/404#issuecomment-394882381 has proven that this is a deeper JAWS/FF bug.

**Comment by jessegreenberg** [comment] 2018-06-05 23:06
We should submit a bug report to VFO. But I am not sure how else to proceed. A few possibilities:
- Ignore this, assume that FF Quantum/JAWS will improve in the next 6 months and hopefully fix this.
- Claim support for  FF ESR with JAWS instead of FF 60.
- Abandon FF with JAWS, support Chrome or Edge instead. Edge is  the latest browser to be claimed as a supported browser by JAWS.
  > JAWS 2018 introduces support for Edge, the latest web browser from Microsoft included in Windows 10. ...we have made the overall experience of navigating pages in Edge using both speech and braille as similar as possible to working in Internet Explorer, Chrome, or Firefox.

@terracoda @emily-phet any thoughts?

**Comment by terracoda** [comment] 2018-06-06 18:10
@jessegreenberg, I am not sure we can completely ignore this? It looks like it could cause the miss firing of sim controls as JAWS is moving focus around. I think you are correct, however, that this problem is going to fix itself.

**Re ESR and FF Support**
If there are no issues with ESR, including this one, we should claim support for ESR, and also claim support with FF 60 with some known issues.

**Re Support for Edge** 
> To use JAWS with Edge, you must be running the Windows 10 Creators update (version 1703) or later. 
Unfortunately, I am not sure how common this ideal environment will be. I think it is too early to abandon support for FF and JAWS. Also, swapping support seems a little premature as everything is in transition.

**Re Chrome Support**
Chrome support seems to have improved a lot, especially Chrome with the ChromeVox plugin. CAn we get a little bit of QA Time to test JAWS and Chrome to see what kinds of issues come up?

**Comment by jessegreenberg** [comment] 2018-06-06 18:22
>  I think it is too early to abandon support for FF and JAWS.

I understand and agree since FF seems to be the most widely used for a11y.

> Can we get a little bit of QA Time to test JAWS and Chrome to see what kinds of issues come up?

If JAWS+Chrome works great, would we be willing to abandon JAWS+FF? If so, this is a great idea.

> If there are no issues with ESR, including this one, we should claim support for ESR, and also claim support with FF 60 with some known issues.

This issue is not in FF ESR, but we will probably find others. But if we did this, the QA team would test FF 60 with NVDA and FF 52 ESR with JAWS? Then every month or so we see if JAWS works in FF quantum?

**Comment by terracoda** [comment] 2018-06-06 18:46
> This issue is not in FF ESR, but we will probably find others that are. But if we did this, the QA team would test FF 60 with NVDA and FF 52 ESR with JAWS? Then every month or so we see if JAWS works in FF quantum?

Oh my goodness, I see the issue now. We do not want 2 versions of FF, one for NVDA and one for JAWS.

If Chrome works great with JAWS, I think we could abandon support for JAWS and FF. Though I think we would need @emily-phet to confirm this decision.

 When I think about it, its not like we are really abandoning for any one Browser, we are telling users that we tested in these browsers and found no issues. Other browsers may have good support, but we can't guarantee it.

**Comment by terracoda** [comment] 2018-06-06 18:50
@jessegreenberg, if we want to support Chrome Books at some pint we will need to test on ChromeVox, too. Lately, I gotta say, ChromeVox has been great in Chrome on MacOs.

**Comment by jessegreenberg** [comment] 2018-06-06 18:54
> When I think about it, its not like we are really abandoning support for any one Browser. We are telling users that we tested in these browsers and found no issues. Other browsers may have good support, but we can't guarantee it.

I totally agree.

> if we want to support Chrome Books at some pint we will need to test on ChromeVox, too. 

Totally agree, once we want to start claiming support for ChromeVox or do user testing on that platform we can add it to the testing matrix.

**Comment by jessegreenberg** [comment] 2018-06-06 18:55
An update is available for my version of JAWS, I am going to update in the off chance this bug as been fixed.

**Comment by terracoda** [comment] 2018-06-06 18:59
@jessegreenberg, one other thought, completely random thought, does the `checkbox` have the same problem if it has an explicit `label`? We swapped the `label` for `aria-label` to reduce repetition. Just wondering if JAWS is having trouble **without** an explicit label.

**Comment by jessegreenberg** [comment] 2018-06-06 19:20
Unfortunately,  it does. I submitted a bug report.

**Comment by terracoda** [comment] 2018-06-06 19:21
@jessegreenberg, can you elaborate on https://github.com/phetsims/balloons-and-static-electricity/issues/404#issuecomment-395183687?

**Comment by jessegreenberg** [comment] 2018-06-06 19:22
Sorry @terracoda, didn't see your last comment.

> Unfortunately, it does. I submitted a bug report.

Was for https://github.com/phetsims/balloons-and-static-electricity/issues/404#issuecomment-395176393.

**Comment by terracoda** [comment] 2018-06-06 21:20
Thanks @jessegreenberg, I will check in with @emily-phet about testing JAWS with Chrome.

**Comment by jessegreenberg** [comment] 2018-06-07 20:02
That sounds great. I am still not sure how we should proceed with immediate deployments, would be good to discuss at an upcomming a11y meeting.

**Comment by jessegreenberg** [comment] 2018-06-08 17:12
Discussed in 6/8/18 meeting:

We will give it a little bit of time to see how VFO responds to the bug. I will also spend a little bit of time searching for a short term workaround to see if it is possible and worth the effort.

**Comment by emily-phet** [comment] 2018-06-08 23:34
@jessegreenberg @terracoda I'll be available Monday to meet. I'll send an email re meeting times.

**Comment by terracoda** [comment] 2018-06-11 13:44
@jessegreenberg AND @emily-phet, I tested master with Chrome and ChromeVox, and it works very well when interacting. 

Reading with the cursor keys is a little awkward due to the way that content lines wrap in the PDOM, but other than that BASE sounds great in Chrome with ChromeVox.

Tested with:
MacBook Pro early 2015
MacOS High Sierra 10.13.4
Chrome Version 67.0.3396.79

**Comment by jessegreenberg** [comment] 2018-06-11 16:39
We discussed on 6/11/18 - 

Since this is a JAWS bug and we expect VFO to fix this bug in the next 4-6 months, we will proceed as we are with support for FF Quantum with JAWS. We will watch the VFO bug reporter in case the VFO team cannot reproduce or decides it is not their issue (like maybe it is a FF bug instead). Marking as wontfix.

@lmulhall-phet is there a good place to document this bug and decision so the QA team is aware of this problem until the AT vendor fixes it? This will show up in all of our sims.

**Comment by lmulhall-phet** [comment] 2018-06-11 16:55
@jessegreenberg, I will inform Jacob! No other testers atm, so that makes it easy.

**Comment by jessegreenberg** [comment] 2018-06-11 17:15
I think we can close this issue. This has been tracked more generally in https://github.com/phetsims/a11y-research/issues/107.

Thanks @lmulhall-phet sounds good.

**Closed by jessegreenberg** 2018-06-11 17:15 UTC
Labels: dev:a11y, type:wontfix
