### ISSUE TITLE
Issue "?stringTest=double" clustered buttons

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balloons-and-static-electricity#88] opened 2015-05-26 17:38 UTC
Testing for Task https://github.com/phetsims/tasks/issues/245
Rest Balloon, Reset, Add Wall/Remove Wall buttons are all very clustered.
![screen shot 2015-05-26 at 11 35 32 am](https://cloud.githubusercontent.com/assets/5631059/7818904/a5f6f510-039b-11e5-8d9e-78e99190be11.png)

**Comment by pixelzoom** [comment] 2016-02-15 21:10
Duplicate of https://github.com/phetsims/balloons-and-static-electricity/issues/115.

**Closed by pixelzoom** 2016-02-15 21:10 UTC
Labels: task:S2015R, type:i18n
