### ISSUE TITLE
Right clicking a balloon causes it to stick 

### ISSUE THREAD

**Issue by arnabp** [phetsims/balloons-and-static-electricity#91] opened 2015-06-17 21:10 UTC
https://drive.google.com/file/d/0BxerAx_XXHB2RE9laGNmUEVIanc/view?usp=sharing

Once I've right clicked on one of the balloons, no matter what I do I cannot let go of the balloon unless I refresh the entire page. I tested this on Mac El Capitan and Yosemite on Chrome and Safari and on a chromebook and all had the issue. When testing on Windows, however, the problem was not there on Chrome nor IE11.

Troubleshooting information (do not edit):
Name: Balloons and Static Electricity
URL: http://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html
Version: 1.0.0
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.32 (KHTML, like Gecko) Version/8.1 Safari/601.1.32
Language: en-us
Window: 1045x1017
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.32)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by samreid** [comment] 2015-06-18 17:12
I recommend some investigation on this before 2015 redeploys, will label it as such.

**Comment by jessegreenberg** [comment] 2018-01-05 19:52
I am not sure if this is still an issue, I will  try to reproduce the problem.

**Comment by lmulhall-phet** [comment] 2018-05-15 18:07
@jessegreenberg I'm able to reproduce using 1.4.0-dev.21 on macOS using Safari, FF, and Chrome. Not able to reproduce on Chrome OS, Win/Edge, Win/FF, or Win/Chrome.

**Comment by terracoda** [comment] 2018-05-30 15:43
@jessegreenberg, if QA was not able to reproduce this issue in dev testing, can we close this issue?

**Comment by jessegreenberg** [comment] 2018-05-30 15:53
@terracoda according to https://github.com/phetsims/balloons-and-static-electricity/issues/91#issuecomment-389260693 it sounds like QA team was able to reproduce this on macOS.

**Comment by terracoda** [comment] 2018-05-30 16:06
@jessegreenberg, thanks. I stand corrected. I read the comment incorrectly.
I'll test Master and see if I can reproduce.

**Comment by terracoda** [comment] 2018-05-30 16:40
Using Mac OS 10.13.4
Safari Version 11.1 (13605.1.33.1.4)
Firefox 60.0.1 (64-bit)
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

@jessegreenberg @lmulhall-phet, I am not able to reproduce this in Safari, Firefox or Chrome, with or with a screen reader on using the version from Master on PhET Test.

What are the steps to reproduce? I just right click on the balloon and nothing out of the ordinary seems to happens.

**Comment by lmulhall-phet** [comment] 2018-05-30 20:15
@terracoda, I also cannot reproduce @arnabp's original issue on master. I can, however, reproduce something similar but slightly more involved than simply right clicking on the balloon. Here are the steps that work for me:
1. Use a mouse.
2. Left click and then immediately right click on the balloon.
3. Exit out of the right click menu by clicking outside of the right click menu. (At this point, the balloon should be stuck to your cursor.)

![base](https://user-images.githubusercontent.com/31285590/40745043-9c60908e-6413-11e8-997d-93c75cd03933.gif)

**Comment by jessegreenberg** [comment] 2018-05-30 20:39
@lmulhall-phet said that https://github.com/phetsims/balloons-and-static-electricity/issues/91#issuecomment-393303200 is just a problem on macOS Chrome.

I tried to reproduce on macOS 10.13.3 and cannot reproduce.

Also, I would be surprised if this issue is specific to BASE, it seems like it could be a problem with anything that uses SimpleDragHandlers (or maybe scenery).

**Comment by jessegreenberg** [comment] 2018-05-30 20:49
@lmulhall-phet showed me how to reproduce - it requires an actual mouse to do it (not a touchpad). He also confirmed that this is a common code issue.

**Comment by jessegreenberg** [comment] 2018-05-30 20:56
A general issue was created for this in scenery https://github.com/phetsims/scenery/issues/803.

This has been noticed elsewhere like https://github.com/phetsims/resistance-in-a-wire/issues/147, and those issues are being closed and deferred. Since this is being tracked generally in scenery Ill close this one too.

**Closed by jessegreenberg** 2018-05-30 20:56 UTC
Labels: priority:5-deferred
