### ISSUE TITLE
Induced Charge "begin to return" read out when moving right (seems random)

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#385] opened 2018-04-05 16:08 UTC
BASE Testing Dragging (Dev 21 - Apr 5)
- [x] Dragging 1 balloon (Show no charges) - no issues
- [x] Dragging 1 balloon (Show charge differences) - no issues
- [x] Dragging 1 balloon (Show all charges) - one issue - Induced charge while dragging, sometimes rad out of order.

Dragging alerts sound great, @jessegreeneberg.

I have not isolated the issue, but the induced charge dragging alerts, "Negative charges in wall begin to return" and "Negative charges in wall return a little more" are read out of order sometimes.

Will use test matrix from https://github.com/phetsims/balloons-and-static-electricity/issues/341#issuecomment-368938070

**Comment by terracoda** [comment] 2018-04-05 17:37
- [ ] JW move left
- [ ] JW move left
- [ ] JN then move up, then move left, then move right
- [ ] JN then move right 
- [ ] JN, then move right, then move left 
- [ ] JN, then move up,/down, then move left 
- [ ] JC when there is a measurable induced charge effect, then move up
- [ ] JC when there is a measurable induced charge effect, then move up, then move left

**Comment by terracoda** [comment] 2018-04-06 16:13
@jessegreenberg, un-assigning you. I am just using this as my testing issue. When I find issues, I will create separate issues for them.

**Comment by terracoda** [comment] 2018-04-09 15:39
@jessegreenberg, I'm not 100% sure, but I think that I am getting the "return a little more" alert incorrectly on a rightward move when vertical movement comes right after the initial return "begin to return" alert.

Trying to reproduce.

**Comment by terracoda** [comment] 2018-04-09 15:40
Hmm, that's not problem. I do not think it is related to vertical movement or jumping.

**Comment by terracoda** [comment] 2018-04-09 15:58
Ok, it seems to happen when I press and hold the Right Arrow key or the D key and stop around the where the induced charge description would begin. This position varies, of course, according to induced charge.

It is not easy to reproduce, but I am able to do it, if I just keep moving back and forth from right to left and left to right and pressing and holding when I move left and right at random distances.

@jessegreenberg, I'm wondering if the simplification for the **Approach alert** (see #389) could help resolve this issue. I updated the notes that support the logic for the Approach and Return alerts in the design document (see https://docs.google.com/document/d/1WNVq5_-Hc9LSdeZVSn2edlwYwpHtGNT1ThFD9NXpZ5Q/edit#heading=h.npqqfbk4ndsn)

I'll copy that here for convenience:
_Logic for the Induced Charge Approach (changed April 9)_
1. First visible movement of charges in wall use **[[move away]]** - (i.e., [+ Induced Charge Dragging (generic)].)
2. Horizontal progression right use **[[move away a little more]]**
3. Vertical dragging with visible induced charge just use [+ Induced Charge Dragging (generic).]

_Logic for the Induced Charge Return (Added clarification April 9 )_
1. First movement left after an induced charge effect has been described (i.e., first movement left after a jump or drag that resulted in an induced charge description) use **[[begin to return]]**
2. Horizontal progression left use **[[return a little more]]**. Repeat until no more describable induced charge effect exists according to model.
3. _If any change in direction (horizontal or vertical)_ , use **[+ Induced Charge Dragging (generic)]**.  (Vertical dragging is the SAME IN BOTH DIRECTIONS).

**Comment by terracoda** [comment] 2018-04-09 16:10
@jessegreenberg, I changed the issues title to be more specific.

**Comment by jessegreenberg** [comment] 2018-04-10 18:57
@terracoda I believe this may have been fixed with the above commit for #398, but  I wasn't able to reproduce originally either. Could you please see if this is still a problem with phettest?

**Comment by terracoda** [comment] 2018-04-12 19:40
@jessegreenberg, I think the fix for #389 has resolved the random utterance of the "begin to return" description when moving right, however, now I hear it when I do a vertical move (up or down) after jumping left away from the wall.

This is easy to reproduce.

Should I start a new issue?

**Comment by terracoda** [comment] 2018-04-12 19:44
To reproduce: 
- get a good charge going on balloon
- jump to wall or near wall
- jump to near wall or center
- move up or move down, and you should hear the incorrect description, "Negative charges begin to return".

**Comment by jessegreenberg** [comment] 2018-04-12 21:35
Excellent, thanks @terracoda! Ill start a new issue because this one has covered many things.

**Closed by jessegreenberg** 2018-04-12 21:35 UTC
Labels: dev:a11y, status:fixed-pending-testing
