### ISSUE TITLE
Splash screen in background of playground

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/balloons-and-static-electricity#427] opened 2018-06-21 15:47 UTC
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.13.5

<b>Browser</b>

Firefox 60.0.2

<b>Problem Description</b>

For phetsims/QA/issues/135. Sometimes the PhET logo and the loading bar from the splash screen appear in the background of the play area. I haven't been able to reproduce this in other browsers, and I haven't been able to reproduce on Arnab's MacBook Pro. I'm wondering if anyone else with macOS 10.13.5 can reproduce.

<b>Steps to Reproduce</b>

1. Load the sim.

(It took me ~10 refreshes to get it to appear on Arnab's MBP.)

<b>Visuals</b>

![screen shot 2018-06-21 at 9 26 30 am 2](https://user-images.githubusercontent.com/31285590/41729913-badaafc4-7537-11e8-83a7-f46036abf0cc.png)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Balloons and Static Electricity‬
URL: https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-rc.1/phet/balloons-and-static-electricity_all_phet.html
Version: 1.4.0-rc.1 2018-06-20 16:57:49 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Language: en-US
Window: 1919x983
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"f0522e7c","branch":"HEAD"},"balloons-and-static-electricity":{"sha":"6aa954ad","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"e8946524","branch":"HEAD"},"dot":{"sha":"6482f8c9","branch":"HEAD"},"joist":{"sha":"22e437d5","branch":"HEAD"},"kite":{"sha":"a1086efc","branch":"HEAD"},"phet-core":{"sha":"17326041","branch":"HEAD"},"phet-io":{"sha":"3ea0727a","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"53708616","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"8a546a32","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"1527afd6","branch":"HEAD"},"phet-io-wrappers":{"sha":"8d814eab","branch":"HEAD"},"phetcommon":{"sha":"6ec8cd89","branch":"HEAD"},"query-string-machine":{"sha":"4182612f","branch":"HEAD"},"scenery":{"sha":"88cb642e","branch":"HEAD"},"scenery-phet":{"sha":"4a1f662e","branch":"HEAD"},"sherpa":{"sha":"88c3b828","branch":"HEAD"},"sun":{"sha":"7579e8fa","branch":"HEAD"},"tandem":{"sha":"8461b6f3","branch":"HEAD"},"vibe":{"sha":"1c92302b","branch":"HEAD"}}

</details>

**Comment by lmulhall-phet** [comment] 2018-06-21 15:52
Update: I am able to reproduce this issue on Arnab's MBP running macOS 10.13.4 on FF 60.0.2.

**Comment by jessegreenberg** [comment] 2018-06-21 16:00
Thanks @lmulhall-phet. This issues doesn't seem  sim specific, are you able to reproduce in any other sims on master?

**Comment by lmulhall-phet** [comment] 2018-06-21 16:01
@jessegreenberg, I will try!

**Comment by lmulhall-phet** [comment] 2018-06-21 16:18
@jessegreenberg, oddly enough, I'm not able to reproduce on other sims in master. I tried John Travoltage, RIAW, and Faraday's Law.

**Comment by jessegreenberg** [comment] 2018-06-21 16:20
OK, thanks for checking @lmulhall-phet - perhaps it is related to the build then. Are you able to reproduce this in BASE on phettest RequireJS? Or any other sims that have been build recently (things in the QA queue maybe). I can take a look too if you don't have time.

**Comment by lmulhall-phet** [comment] 2018-06-21 16:24
> Are you able to reproduce this in BASE on phettest RequireJS?

No.

Checking other recently built sims...

**Comment by lmulhall-phet** [comment] 2018-06-21 16:29
> Or any other sims that have been build recently (things in the QA queue maybe).

No.

**Comment by terracoda** [comment] 2018-06-21 19:06
@lmulhall-phet, I have never seen this on any sim. I've seen focus highlights stick around, but never the splash screen logo.

**Comment by jessegreenberg** [comment] 2018-06-21 21:41
So it sounds like this is ONLY happening in BASE built version.

**Comment by jessegreenberg** [comment] 2018-06-21 21:43
I just saw this happen once in Windows FF after 7 refreshes.

**Comment by jessegreenberg** [comment] 2018-06-21 21:46
In the console when this happens:
![capture](https://user-images.githubusercontent.com/6396244/41747144-2ce83e1a-756a-11e8-917e-e1d5fdadc951.PNG)

The sim is still usable.

**Comment by jessegreenberg** [comment] 2018-06-21 21:47
Canvas is being used to draw the charges as images.
```js
        context.drawImage( this.chargeImageNode.image, xPosition, yPosition );
```
This was added for performance reasons. I wonder if we will this happen in other sims that are using canvas.

**Comment by jessegreenberg** [comment] 2018-06-21 22:47
I believe the issue is that we are converting the charge Nodes to be drawn by Canvas, but `toImage` is asynchronous, so there is a change that the image hasn't been created yet by the time that we are painting the canvas.

**Comment by jessegreenberg** [comment] 2018-06-21 22:57
`Node.rasterized` might be what we need to create a scenery Image node synchronously.

**Comment by jessegreenberg** [comment] 2018-06-21 23:09
Should be fixed in the above commit, this was a problem with the way I was using canvas, and even more strange that it was only happening in FF. Anyway, I tried refreshing the sim 20 times with the above change and couldn't get it to happen in a built version of the sim. This commit will need to be merged into release branch.

**Comment by jessegreenberg** [comment] 2018-06-27 17:00
In the above issue @lmulhall-phet said:
>...after refreshing 20+ times, I wasn't able to reproduce.
>Looks good on:
  macOS + FF
  macOS + Chrome
  macOS + Safari
  Win10 + FF
  Win10 + Chrome
  Win10 + Edge
  iOS + Safari
  Chrome OS + Chrome
  Android + Chrome

This issue can be closed.

**Closed by jessegreenberg** 2018-06-27 17:00 UTC
Labels: status:fixed-pending-testing, type:bug
