### ISSUE TITLE
Visual charge pick up and alert charge announcement out of synch

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#208] opened 2016-11-18 19:27 UTC
Need to explore further whether the visual charge pick is synchronized with the alerts about charge pick up.

**Comment by terracoda** [comment] 2016-11-18 19:29
@terracoda just noticed that moving the balloon left on sweater visually picked up several charges, but "No change in charges was announced." Moving back to the right, no charges were picked up, but the alert said there were charges picked up.

Was using MacOS Sierra and ChromeVox. I've seen this before, and will investigate further.

**Comment by jessegreenberg** [comment] 2016-11-21 17:18
@terracoda I tried for a little why to reproduce this issue, but I haven't been able to make it happe.  If you are able to observe this consistently, can you please let me know the conditions to recreate the issue and assign to me?

**Comment by terracoda** [comment] 2016-11-21 18:39
@jessegreenberg, yes, I'm going to explore this issue further, and get back to you. It is not high priority, as the information is consistent. It just seemed like the visual was out of synch from the actual description.

**Comment by jessegreenberg** [comment] 2016-11-22 01:23
@terracoda I would assume that this issue is caused by the same problem as #207.  I added some comments about why I think this is happening here: https://github.com/phetsims/balloons-and-static-electricity/issues/207#issuecomment-262119486

**Comment by jessegreenberg** [comment] 2016-12-06 01:10
@terracoda this presumably the same issue as #207 which has now been closed.  If you ever run into this again in later versions please reopen this issue and let me know.

**Closed by jessegreenberg** 2016-12-06 01:10 UTC
Labels: dev:a11y, type:bug
