### ISSUE TITLE
Embedding sim hangs at loading screen

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balloons-and-static-electricity#93] opened 2015-08-05 17:55 UTC
Via user:
The problem with opening the embed sim only appears in Internet Explorer; the sim loads fine with chrome, firefox, android browsers etc.  The sim also opens normally using the play button from the sims page - even in internet explorer
 
I have stripped things back to basics for the purpose of diagnostics, so the code I am using is:
 
<html>
<iframe src="http://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html" width="800" height="600" allowfullscreen></iframe>
</html>

Report a Problem

Please copy and paste the information below into an email to phethelp@colorado.edu, and then fill in the blanks. 

Test device:

Lenovo Flex2-15 i7-4510, 16GB RAM, Windows 8.1
(Problem also present on Medion i3 w/4GB RAM & Windows 7, and Sempron w/4GB & Windows Vista)
 
 
Operating System:

Windows 8.1

Browser:

Internet Explorer 11

Problem description:

Embedded "balloons and electricity" simulation stops at PhET splash screen, with the words "loading"

Steps to reproduce:

open any page containing the embed code for the simulation, using Internet Explorer browser.

Severity:

Prevents successful embedding of simulation.

Screenshots:

Embedded simulation does not load.
![phet single embedded applet - screenshot ie](https://cloud.githubusercontent.com/assets/5090275/9093325/c371c0e8-3b68-11e5-91c4-8f2f9da9552d.jpg)
![phet embedded applets - screenshot ie](https://cloud.githubusercontent.com/assets/5090275/9093329/c8229928-3b68-11e5-8077-c7756bf98d89.jpg)
 
Other embedded simulations load fine...
   
Troubleshooting information (do not edit):

Name: Balloons and Static Electricity
URL: https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html
Version: 1.0.0
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; Tablet PC 2.0; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; McAfee; GWX:DOWNLOADED; LCJB; rv:11.0) like Gecko
Language: en-GB
Window: 1536x726
Pixel Ratio: 1.25/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by samreid** [comment] 2015-08-08 04:56
I'll publish a fresh dev version and test the iframe on IE.

**Comment by samreid** [comment] 2015-08-08 05:11
I published here:
http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-dev.1/balloons-and-static-electricity_en-iframe.html

![image](https://cloud.githubusercontent.com/assets/679486/9149164/76528908-3d59-11e5-838a-8e138679c597.png)

So I am unable to reproduce the problem on IE11 with a fresh build.  @oliver-phet can you ask the client to test the link above and report back?  If it fails, please instruct them to open the JavaScript console and look for errors.

**Comment by oliver-phet** [comment] 2015-08-13 16:24
Email from user sent 8/13:
The link you sent me works fine.  Does this help us diagnose/fix the problem?

**Comment by samreid** [comment] 2015-08-13 16:32
If it is fixed in the latest version, perhaps we will have to wait for the upcoming S2015R redeploys before this fix will be published to our website.

**Comment by oliver-phet** [comment] 2015-08-13 18:35
Email to user sent 8/13... this fix will be apart of the S2015R.

**Comment by samreid** [comment] 2015-12-09 20:21
Reopening until this is actually fixed.

**Comment by oliver-phet** [comment] 2016-05-12 18:42
@samreid Can this issue now be closed?

**Comment by samreid** [comment] 2016-05-12 23:15
It looks like this sim was redeployed as Version 1.1.2 in April, closing.

**Closed by samreid** 2016-05-12 23:15 UTC
