### ISSUE TITLE
'ar' and 'ar_SA' string files look wrong

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#94] opened 2015-08-21 01:09 UTC
These are in babel. They look like they are for some other sim - different keys, title key is "balloons-and-buoyancy.name".  

Assigning to @samreid to have a look since he was lead on this sim.

**Comment by pixelzoom** [comment] 2015-08-21 01:09
Is it possible that these were checked in incorrectly to SVN for the Java version?

**Comment by pixelzoom** [comment] 2015-08-25 16:50
These string files are indeed also incorrect for the Java version (in Unfuddle SVN).  The comment header in the Java string files is:

```
#balloons-and-buoyancy created Wed May 13 23:11:00 AST 2009 using: ideal-gas 3.08.00 (17033), translation-utility 1.11.00 (29003)
#Wed May 13 23:11:00 AST 2009
```

So they are for `ideal-gas`.  I'm guessing that someone was confused by the title "Balloons and Buoyancy" and thought that those translations belonged in the "balloons" project.

**Comment by pixelzoom** [comment] 2015-08-25 16:52
An issue for this should probably be created in Unfuddle.  The 'ar' and 'ar_SA' versions of "Balloons and Static Electricity" is likely deployed with the wrong string files.  And ideal-gas didn't get deployed with these string files.

**Comment by samreid** [comment] 2015-08-26 22:27
I checked those string files and confirmed they didn't have any balloons-and-static-electricity strings, so I deleted them from babel.  We'll get new ar and ar_sa translations when rosetta rolls out.  I'll take a look at the published java version next.

**Comment by samreid** [comment] 2015-08-26 22:30
Indeed, only the common strings are translated.  I'm somewhat inclined to leave this alone since (a) we have published the HTML version of the sim and (b) we have received no error reports about this and (c) I am uncertain how much work this would be to resolve on the website-- @aaronsamuel137 or @jonathanolson would know how to answer that.  
![image](https://cloud.githubusercontent.com/assets/679486/9508022/ac7be802-4c0f-11e5-837a-ac982f3e58c2.png)

I'll unassign and wait for a +1 to close as-is, or a +1 to "we should solve this before we move on".

**Comment by aaronsamuel137** [comment] 2015-08-27 13:58
+1 to close as is.

**Comment by pixelzoom** [comment] 2015-08-27 16:18
No preference. Probably a management decision.

**Comment by samreid** [comment] 2015-08-27 16:23
I'll reopen to see if @kathy-phet @ariel-phet or @oliver-phet wants to comment.

**Comment by samreid** [comment] 2015-08-27 16:52
@kathy-phet suggested to reinstate the ar and ar_sa translations.

**Comment by samreid** [comment] 2015-09-04 15:56
I checked the history of svn and there are no ar or ar_SA submissions for balloons-and-static-electricity.  I checked and the ideal-gas subproject balloons-and-buoyancy has both translations.  So all that's left to do here is to (a) remove the ar and ar_SA translations of balloons-and-static-electricity from the website or (b) get a translator to retranslate them.   Reassigned to @aaronsamuel137 to see if (a) is a good plan.

**Comment by aaronsamuel137** [comment] 2015-09-05 15:51
I'm not totally sure what the best way of removing these from the website is... perhaps @jonathanolson can comment.

The easiest thing I can think of it to remove those locales from the balloons.xml file and resynchronize the project, and I guess delete the jar and jnlp files too if that won't cause issues. Does this sound like the right approach @jonathanolson?

**Comment by samreid** [comment] 2015-10-08 16:23
It looks like @aaronsamuel137 is awaiting feedback from @jonathanolson so I'll assign it to him.

**Comment by jessegreenberg** [comment] 2018-05-15 15:53
Assigning to myself to discuss status of this issue with @jbphet.

**Comment by jbphet** [comment] 2018-05-15 17:27
There are no HTML5 translations of this sim in babel, nor on the website, for the two locales specified ('ar' and 'ar_SA').  In other words, there is nothing that needs to be addressed for rosetta or anything related to HTML5 translations.

There are other comments above about problems with the translations of the Java version of this sim.  It seems those translations are partial, as shown in the screenshot above.  This issue was assigned to @jonathanolson a couple of years ago in an effort to determine whether it was worth the time and effort to delete the partial translations of the Java sim, but it wasn't addressed, likely due to low prioritization.  We should probably just close the issue, since no one has complained and if they did, we'd tell them to use rosetta and submit a new translation.  I'm not comfortable unilaterally closing this without making sure that @ariel-phet concurs, so I'm assigning it to him.  @ariel-phet - please close or assign to @jonathanolson as you see fit.

**Comment by ariel-phet** [comment] 2018-05-18 18:07
@jbphet I agree this can be closed, and certainly nothing needs to be done on the Java side.

Closing

**Closed by ariel-phet** 2018-05-18 18:07 UTC
Labels: type:bug
