### ISSUE TITLE
Radio buttons are too large

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balloons-and-static-electricity#95] opened 2015-10-06 17:29 UTC
We now have much more reasonable sized radio buttons, the radio buttons in the sim should be reduced in visual size to aesthetically match our newer sims

**Comment by samreid** [comment] 2015-10-08 16:25
Since this shouldn't take too long, I recommend doing it before S2015R, I'll label the issue as such.

**Comment by jessegreenberg** [comment] 2016-12-08 01:53
This is a duplicate of #212, closing.

**Closed by jessegreenberg** 2016-12-08 01:53 UTC
Labels: dev:enhancement
