### ISSUE TITLE
Visual negative charges off by one.

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#131] opened 2016-02-19 01:49 UTC
I understand that the charge representations are metaphorical. However, I noticed that a balloon can have a net negative charge, but appear in the visual as a net zero charge. This occurred in one of my interviews. The Yellow Balloon had collected all but one of the negative charges. The Green Balloon then collected the last negative charge. In the description the Green Balloon became negatively charged, but in the visual it didn't.

And , of course, it behaved as a balloon with net negative charge.

I did some further testing, and it looks like the negative charges are always off by one.

**Comment by jessegreenberg** [comment] 2016-02-19 18:00
Related to issue #79.

This issue can be reproduced in master and 1.0 published to site.  As @terracoda suggests, it looks like visible charges on balloon are always one less than they should be.   Exemplified with 'show charge differences' selected:
![charge-differences-2](https://cloud.githubusercontent.com/assets/6396244/13184252/fc49dc4a-d6f7-11e5-97d0-6a43b4fb6e0b.PNG)

**Comment by jessegreenberg** [comment] 2016-02-20 01:09
In BalloonNode:

```js
    //if change charge, show more minus charges
    model.chargeProperty.link( function updateLocation( chargeVal ) {
      if ( chargeVal ) {
        model.minusCharges[ model.plusCharges.length - 1 - chargeVal - 1 ].view.visible = true;
      }
    } );
```

I think ```model.plusCharges.length - 1 - chargeVal - 1``` is one less than it should be.  ```model.plusCharges.length - chargeVal - 1``` gives the difference in positive and negative charges, minus one for the array index offset.

**Comment by jessegreenberg** [comment] 2016-02-20 01:18
Fixed in commit above.  The balloon should now always have an electron when it has charge.  A few of the ChargeNodes overlap exactly, so after about charge 8, it may look like the the visible charge is off by one or two.  @arouinfar is this acceptable or should all charges have unique locations?

**Comment by arouinfar** [comment] 2016-02-22 18:33
@jessegreenberg that seems like a reasonable solution to me. I haven't noticed students counting the number of electrons on the balloons when there are more than just a few electrons present.

**Comment by jessegreenberg** [comment] 2016-02-22 21:22
Great, thanks @arouinfar.  Closing.

**Closed by jessegreenberg** 2016-02-22 21:22 UTC
Labels: type:bug
